[package]
name = "ripple"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hostname = "0.3.1"
local-ip-address = "0.5.7"
mac_address = "1.1.5"
